# Generated by Django 4.1.7 on 2023-05-10 01:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("UserAuthentication", "0009_alter_lawyer_lawyer_category"),
        ("LawyerManagement", "0003_paymentplan"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, null=True)),
                (
                    "thumbnail",
                    models.ImageField(blank=True, null=True, upload_to="payment_paln/"),
                ),
                ("image_text", models.CharField(default="", max_length=101)),
                ("note", models.CharField(blank=True, max_length=100, null=True)),
                ("is_archived", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="PaymentHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("pending for lawyer", "Pending For Lawyer"),
                        ],
                        default="pending",
                        max_length=19,
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("pending for lawyer", "Pending For Lawyer"),
                        ],
                        default="pending",
                        max_length=19,
                    ),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "approved_by",
                    models.CharField(blank=True, default="", max_length=65, null=True),
                ),
                (
                    "created_by",
                    models.CharField(blank=True, default="", max_length=65, null=True),
                ),
                ("note", models.CharField(blank=True, max_length=100, null=True)),
                ("is_archived", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "chosenPaymentPlan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="LawyerManagement.paymentplan",
                    ),
                ),
                (
                    "lawyer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="UserAuthentication.lawyer",
                    ),
                ),
                (
                    "paymentMethod",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="Payment.paymentmethod",
                    ),
                ),
            ],
        ),
    ]
