# Generated by Django 4.1.7 on 2023-05-10 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Payment", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentmethod",
            name="order",
            field=models.IntegerField(default=0),
        ),
    ]
