# Generated by Django 4.1.7 on 2023-05-10 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Payment", "0002_paymentmethod_order"),
    ]

    operations = [
        migrations.RenameField(
            model_name="paymenthistory",
            old_name="chosenPaymentPlan",
            new_name="chosen_payment_plan",
        ),
        migrations.RemoveField(
            model_name="paymenthistory",
            name="paymentMethod",
        ),
        migrations.AddField(
            model_name="paymenthistory",
            name="transaction_number",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="paymenthistory",
            name="payment_method",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="Payment.paymentmethod",
            ),
        ),
    ]
