# Generated by Django 4.1.7 on 2023-04-27 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("EventManagement", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Events",
            new_name="Event",
        ),
    ]
