# Generated by Django 4.1.7 on 2023-05-03 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("EventManagement", "0003_alter_event_end_time_alter_event_start_time"),
    ]

    operations = [
        migrations.RenameField(
            model_name="event",
            old_name="end_time",
            new_name="end_Date",
        ),
        migrations.RenameField(
            model_name="event",
            old_name="start_time",
            new_name="start_Date",
        ),
    ]
