# Generated by Django 4.1.7 on 2023-05-03 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("EventManagement", "0004_rename_end_time_event_end_date_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="event",
            old_name="end_Date",
            new_name="end_time",
        ),
        migrations.RenameField(
            model_name="event",
            old_name="start_Date",
            new_name="start_time",
        ),
    ]
