# Generated by Django 4.1.7 on 2023-05-04 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("UserAuthentication", "0004_remove_lawyer_lawyer_type_lawyer_lawyer_type"),
        ("LawyerManagement", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="LawyerType",
            new_name="LawyerCategory",
        ),
    ]
