# Generated by Django 4.1.7 on 2023-05-05 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("LawyerManagement", "0002_rename_lawyertype_lawyercategory"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, null=True)),
                (
                    "thumbnail",
                    models.ImageField(blank=True, null=True, upload_to="payment_paln/"),
                ),
                ("image_text", models.CharField(default="", max_length=101)),
                (
                    "balance",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
                ),
                ("duration", models.IntegerField(default=0)),
                ("order", models.IntegerField(default=0)),
                (
                    "duration_type",
                    models.CharField(
                        choices=[
                            ("Day", "Day"),
                            ("Month", "Month"),
                            ("Week", "Week"),
                            ("Year", "Year"),
                        ],
                        default="Day",
                        max_length=9,
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=100, null=True)),
                ("is_archived", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
