# Generated by Django 4.1.7 on 2023-03-12 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('user', models.CharField(max_length=250)),
                ('user_ip', models.CharField(max_length=100)),
                ('action_name', models.CharField(max_length=50)),
                ('table_name', models.CharField(blank=True, max_length=250, null=True)),
                ('task_name', models.CharField(blank=True, max_length=50, null=True)),
                ('action_details', models.CharField(blank=True, max_length=200, null=True)),
                ('data', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
