# Generated by Django 4.1.7 on 2023-04-27 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TeamMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="", max_length=101)),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True, null=True, upload_to="law_thumbnail/"
                    ),
                ),
                ("image_text", models.CharField(default="", max_length=101)),
                ("order", models.IntegerField(default=0)),
                ("slug", models.CharField(default="", max_length=101)),
                ("description", models.TextField(default="")),
                ("Designation", models.CharField(default="", max_length=543)),
                ("is_archived", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
