# Generated by Django 4.1.7 on 2023-04-27 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TeamManagement", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="teammember",
            old_name="Designation",
            new_name="designation",
        ),
        migrations.AddField(
            model_name="teammember",
            name="portfolio_url",
            field=models.CharField(default="", max_length=250),
        ),
    ]
