# Generated by Django 4.1.7 on 2023-04-02 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Law',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=101)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='law_thumbnail/')),
                ('image_text', models.CharField(default='', max_length=101)),
                ('order', models.IntegerField(default=0)),
                ('url', models.CharField(default='', max_length=101)),
                ('description', models.TextField(default='')),
                ('headline', models.CharField(default='', max_length=543)),
                ('home_law', models.BooleanField(default=False)),
                ('is_archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
