# Generated by Django 4.1.7 on 2023-03-15 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LawManagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='law',
            name='headline',
            field=models.CharField(default='', max_length=543),
        ),
    ]
