# Generated by Django 4.1.7 on 2023-04-25 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("LawManagement", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="law",
            old_name="url",
            new_name="slug",
        ),
    ]
