# Generated by Django 4.1.7 on 2024-01-20 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RegularPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "page_name",
                    models.CharField(
                        choices=[
                            ("About us", "About Us"),
                            ("Terms and Conditions", "T And C"),
                        ],
                        default="About us",
                        max_length=113,
                    ),
                ),
                ("page_view", models.TextField(default="")),
                ("is_archived", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
