# Generated by Django 4.1.7 on 2024-01-21 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("RegularPages", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="regularpage",
            name="updated_by",
            field=models.CharField(default="-", max_length=250),
            preserve_default=False,
        ),
    ]
