# Generated by Django 4.1.7 on 2023-03-24 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HelpCenter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='helpcenter',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
