# Generated by Django 4.1.7 on 2023-05-04 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("HelpCenter", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CallHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True, null=True, upload_to="help_line_rules/"
                    ),
                ),
                ("image_text", models.CharField(default="", max_length=101)),
                ("helpline", models.CharField(default="", max_length=101)),
                ("rules", models.TextField(default="")),
                ("is_archived", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
