# Generated by Django 4.1.7 on 2023-05-04 21:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("UserAuthentication", "0007_alter_lawyer_lawyer_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("HelpCenter", "0002_callhistory"),
    ]

    operations = [
        migrations.RenameField(
            model_name="callhistory",
            old_name="helpline",
            new_name="recorded_file_info",
        ),
        migrations.RemoveField(
            model_name="callhistory",
            name="image_text",
        ),
        migrations.RemoveField(
            model_name="callhistory",
            name="rules",
        ),
        migrations.RemoveField(
            model_name="callhistory",
            name="thumbnail",
        ),
        migrations.AddField(
            model_name="callhistory",
            name="comments",
            field=models.CharField(default="", max_length=543),
        ),
        migrations.AddField(
            model_name="callhistory",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="UserAuthentication.customer",
            ),
        ),
        migrations.AddField(
            model_name="callhistory",
            name="minutes",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="callhistory",
            name="received_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
