# Generated by Django 4.1.7 on 2023-08-11 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("HelpCenter", "0003_rename_helpline_callhistory_recorded_file_info_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="callhistory",
            name="no_customers_mobile",
            field=models.CharField(default="", max_length=19),
        ),
    ]
