# Generated by Django 4.1.7 on 2023-08-16 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("UserAuthentication", "0012_rename_customer_pic_customer_image"),
        ("HelpCenter", "0004_callhistory_no_customers_mobile"),
    ]

    operations = [
        migrations.AddField(
            model_name="callhistory",
            name="lawyer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="UserAuthentication.lawyer",
            ),
        ),
    ]
