# Generated by Django 4.1.7 on 2023-05-04 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Appoinment", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Zone",
        ),
    ]
