# Generated by Django 4.1.7 on 2023-05-04 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Appoinment", "0003_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentplan",
            name="order",
            field=models.IntegerField(default=0),
        ),
    ]
