# Generated by Django 4.1.7 on 2023-05-05 00:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("UserAuthentication", "0008_alter_lawyer_payment_plan"),
        ("Appoinment", "0004_paymentplan_order"),
    ]

    operations = [
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.CharField(default="", max_length=543)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("pending", "Pending"),
                            ("hold", "Hold"),
                            ("active", "Accepted"),
                            ("deactivated", "Rejected"),
                            ("deleted", "Deleted"),
                        ],
                        default="pending",
                        max_length=15,
                    ),
                ),
                ("status_changed_by", models.CharField(default="", max_length=100)),
                ("is_archived", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="UserAuthentication.customer",
                    ),
                ),
                (
                    "lawyer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="UserAuthentication.lawyer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AppointmentComments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.CharField(default="", max_length=543)),
                ("is_archived", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="UserAuthentication.customer",
                    ),
                ),
                (
                    "lawyer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="Appoinment.appointment",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="PaymentPlan",
        ),
    ]
