# Generated by Django 4.1.7 on 2023-05-06 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Appoinment", "0005_appointment_appointmentcomments_delete_paymentplan"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="chosen_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
