# Generated by Django 4.1.7 on 2023-05-08 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Appoinment", "0006_appointment_chosen_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("deleted", "Deleted"),
                ],
                default="pending",
                max_length=15,
            ),
        ),
    ]
