# Generated by Django 4.1.7 on 2023-06-13 01:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("UserAuthentication", "0012_rename_customer_pic_customer_image"),
        ("Appoinment", "0007_alter_appointment_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="AppointmentComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.CharField(default="", max_length=543)),
                ("is_archived", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "appointment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="Appoinment.appointment",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="UserAuthentication.customer",
                    ),
                ),
                (
                    "lawyer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="UserAuthentication.lawyer",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="AppointmentComments",
        ),
    ]
