# Generated by Django 4.1.7 on 2023-07-03 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("LawyerManagement", "0003_paymentplan"),
        ("Appoinment", "0008_appointmentcomment_delete_appointmentcomments"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="lawyer_category",
            field=models.ManyToManyField(to="LawyerManagement.lawyercategory"),
        ),
    ]
