# Generated by Django 4.1.7 on 2023-07-14 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Appoinment", "0009_appointment_lawyer_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="Appointment_num",
            field=models.CharField(default="", max_length=15),
        ),
    ]
