# Generated by Django 4.1.7 on 2023-09-22 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Appoinment", "0010_appointment_appointment_num"),
    ]

    operations = [
        migrations.RenameField(
            model_name="appointment",
            old_name="Appointment_num",
            new_name="appointment_num",
        ),
    ]
