# Generated by Django 4.1.7 on 2023-03-11 08:28

import RoleAssignment.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RoleAssignment', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userwithrole',
            name='picture',
            field=models.ImageField(default='media/userimg/default.png', upload_to=RoleAssignment.models.upload_location),
        ),
    ]
