# Generated by Django 4.1.7 on 2023-03-25 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('LawManagement', '0002_law_headline'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowYourLaw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=60)),
                ('answer', models.TextField()),
                ('tags', models.CharField(max_length=60)),
                ('is_archived', models.BooleanField(default=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('law', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='LawManagement.law')),
            ],
        ),
    ]
