# Generated by Django 4.1.7 on 2023-06-13 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("KnowYourLaw", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="knowyourlaw",
            name="question",
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name="knowyourlaw",
            name="tags",
            field=models.CharField(max_length=150),
        ),
    ]
