# Generated by Django 4.1.7 on 2023-03-26 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KnowYourLaw', '0002_knowyourlaw_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='knowyourlaw',
            name='answer',
        ),
        migrations.AddField(
            model_name='knowyourlaw',
            name='ban_answer',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='knowyourlaw',
            name='eng_answer',
            field=models.TextField(default=''),
        ),
    ]
