# Generated by Django 4.1.7 on 2023-04-02 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('mobile', models.CharField(max_length=15, null=True)),
                ('email', models.CharField(max_length=100, null=True)),
                ('password', models.CharField(max_length=1000, null=True)),
                ('apartment', models.CharField(default='', max_length=300)),
                ('street_address', models.CharField(default='', max_length=300)),
                ('city', models.CharField(default='', max_length=300)),
                ('country', models.CharField(default='', max_length=300)),
                ('latitude', models.CharField(max_length=1000, null=True)),
                ('longitude', models.CharField(max_length=1000, null=True)),
                ('cardno', models.CharField(default='', max_length=250)),
                ('gender', models.CharField(default='', max_length=15)),
                ('customer_type', models.PositiveSmallIntegerField(default=0)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('is_archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.CharField(max_length=250)),
                ('code', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('resend_count', models.IntegerField(default=0)),
                ('is_mobile', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=True)),
                ('is_archived', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
