# Generated by Django 4.1.7 on 2023-04-27 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("UserAuthentication", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Lawyer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, null=True)),
                ("mobile", models.CharField(max_length=15, null=True)),
                ("email", models.CharField(max_length=100, null=True)),
                ("password", models.CharField(max_length=1000, null=True)),
                ("apartment", models.CharField(default="", max_length=300)),
                ("street_address", models.CharField(default="", max_length=300)),
                ("city", models.CharField(default="", max_length=300)),
                ("country", models.CharField(default="", max_length=300)),
                ("latitude", models.CharField(max_length=1000, null=True)),
                ("longitude", models.CharField(max_length=1000, null=True)),
                ("cardno", models.CharField(default="", max_length=250)),
                ("gender", models.CharField(default="", max_length=15)),
                ("lawyer_type", models.PositiveSmallIntegerField(default=0)),
                (
                    "balance",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
                ),
                ("is_archived", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
