# Generated by Django 4.1.7 on 2023-04-27 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("UserAuthentication", "0002_lawyer"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="customer_pic",
            field=models.ImageField(blank=True, null=True, upload_to="customer_pic/"),
        ),
        migrations.AddField(
            model_name="customer",
            name="image_text",
            field=models.CharField(default="", max_length=101),
        ),
        migrations.AddField(
            model_name="lawyer",
            name="image_text",
            field=models.CharField(default="", max_length=101),
        ),
        migrations.AddField(
            model_name="lawyer",
            name="lawyer_pic",
            field=models.ImageField(blank=True, null=True, upload_to="lawyer_pic/"),
        ),
    ]
