# Generated by Django 4.1.7 on 2023-05-03 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("LawyerManagement", "0001_initial"),
        (
            "UserAuthentication",
            "0003_customer_customer_pic_customer_image_text_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lawyer",
            name="lawyer_type",
        ),
        migrations.AddField(
            model_name="lawyer",
            name="lawyer_type",
            field=models.ManyToManyField(to="LawyerManagement.lawyertype"),
        ),
    ]
