# Generated by Django 4.1.7 on 2023-05-04 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Address", "0001_initial"),
        ("LawyerManagement", "0002_rename_lawyertype_lawyercategory"),
        ("UserAuthentication", "0004_remove_lawyer_lawyer_type_lawyer_lawyer_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="apartment",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="city",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="country",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="latitude",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="longitude",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="street_address",
        ),
        migrations.RemoveField(
            model_name="lawyer",
            name="apartment",
        ),
        migrations.RemoveField(
            model_name="lawyer",
            name="city",
        ),
        migrations.RemoveField(
            model_name="lawyer",
            name="country",
        ),
        migrations.RemoveField(
            model_name="lawyer",
            name="latitude",
        ),
        migrations.RemoveField(
            model_name="lawyer",
            name="longitude",
        ),
        migrations.RemoveField(
            model_name="lawyer",
            name="street_address",
        ),
        migrations.AddField(
            model_name="customer",
            name="address",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="Address.address",
            ),
        ),
        migrations.AddField(
            model_name="lawyer",
            name="address",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="Address.address",
            ),
        ),
        migrations.AddField(
            model_name="lawyer",
            name="lawyer_category",
            field=models.ManyToManyField(to="LawyerManagement.lawyercategory"),
        ),
        migrations.AlterField(
            model_name="customer",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("Male", "Male"), ("Female", "Female"), ("Other", "Other")],
                default="",
                max_length=9,
            ),
        ),
        migrations.AlterField(
            model_name="lawyer",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("Male", "Male"), ("Female", "Female"), ("Other", "Other")],
                default="",
                max_length=9,
            ),
        ),
        migrations.RemoveField(
            model_name="lawyer",
            name="lawyer_type",
        ),
        migrations.AddField(
            model_name="lawyer",
            name="lawyer_type",
            field=models.CharField(
                blank=True,
                choices=[("lawyer", "Lawyer"), ("lawfarm", "Lawfarm")],
                default="lawyer",
                max_length=9,
            ),
        ),
    ]
