# Generated by Django 4.1.7 on 2023-05-04 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Appoinment", "0003_initial"),
        (
            "UserAuthentication",
            "0005_remove_customer_apartment_remove_customer_city_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="lawyer",
            old_name="lawyer_pic",
            new_name="image",
        ),
        migrations.AddField(
            model_name="customer",
            name="nid",
            field=models.CharField(max_length=23, null=True),
        ),
        migrations.AddField(
            model_name="lawyer",
            name="bar_council_number",
            field=models.CharField(max_length=33, null=True),
        ),
        migrations.AddField(
            model_name="lawyer",
            name="nid",
            field=models.CharField(max_length=23, null=True),
        ),
        migrations.AddField(
            model_name="lawyer",
            name="payment_plan",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="Appoinment.paymentplan",
            ),
        ),
        migrations.AddField(
            model_name="lawyer",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("pending", "Pending"),
                    ("hold", "Hold"),
                    ("active", "Active"),
                    ("deactivated", "Deactivated"),
                    ("deleted", "Deleted"),
                ],
                default="pending",
                max_length=15,
            ),
        ),
        migrations.AddField(
            model_name="lawyer",
            name="tradelicense",
            field=models.CharField(max_length=23, null=True),
        ),
    ]
