# Generated by Django 4.1.7 on 2023-05-04 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "UserAuthentication",
            "0006_rename_lawyer_pic_lawyer_image_customer_nid_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="lawyer",
            name="lawyer_type",
            field=models.CharField(
                blank=True,
                choices=[("lawyer", "Lawyer"), ("lawfirm", "Lawfirm")],
                default="lawyer",
                max_length=9,
            ),
        ),
    ]
