# Generated by Django 4.1.7 on 2023-05-05 00:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("LawyerManagement", "0003_paymentplan"),
        ("UserAuthentication", "0007_alter_lawyer_lawyer_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lawyer",
            name="payment_plan",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="LawyerManagement.paymentplan",
            ),
        ),
    ]
