# Generated by Django 4.1.7 on 2023-05-12 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("UserAuthentication", "0010_lawyer_expiary_date_lawyer_warning_day"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lawyer",
            name="expiary_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
