# Generated by Django 4.1.7 on 2023-05-24 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("UserAuthentication", "0011_alter_lawyer_expiary_date"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customer",
            old_name="customer_pic",
            new_name="image",
        ),
    ]
