# Generated by Django 4.1.7 on 2023-09-16 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("UserAuthentication", "0012_rename_customer_pic_customer_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="customer_id",
            field=models.CharField(default="", max_length=15),
        ),
        migrations.AddField(
            model_name="lawyer",
            name="lawyer_id",
            field=models.CharField(default="", max_length=15),
        ),
    ]
