# Generated by Django 4.1.7 on 2024-01-06 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("UserAuthentication", "0013_customer_customer_id_lawyer_lawyer_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="lawyer",
            name="status_changed_at",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="lawyer",
            name="status_changed_by",
            field=models.CharField(default="", max_length=100),
        ),
    ]
