# Generated by Django 4.1.7 on 2023-05-04 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Address", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="zone",
            name="latitude",
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name="zone",
            name="longitude",
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
