# Generated by Django 4.1.7 on 2023-05-04 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Address", "0002_zone_latitude_zone_longitude"),
    ]

    operations = [
        migrations.AlterField(
            model_name="zone",
            name="latitude",
            field=models.CharField(default=None, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="zone",
            name="longitude",
            field=models.CharField(default=None, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="zone",
            name="note",
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
