# Generated by Django 4.1.7 on 2023-05-04 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Address", "0003_alter_zone_latitude_alter_zone_longitude_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="zone",
            name="latitude",
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="zone",
            name="longitude",
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="zone",
            name="note",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
