# Generated by Django 4.1.7 on 2023-05-04 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Address", "0005_alter_zone_latitude_alter_zone_longitude_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="zone",
            name="zone_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("division", "Division"),
                    ("district", "District"),
                    ("thana", "Thana"),
                ],
                default="thana",
                max_length=9,
            ),
        ),
    ]
