# Generated by Django 4.1.7 on 2023-04-02 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
                ('image', models.FileField(blank=True, null=True, upload_to='slider/')),
                ('mobile_image', models.FileField(blank=True, null=True, upload_to='slider/')),
                ('start_date', models.DateTimeField(null=True)),
                ('end_date', models.DateTimeField(null=True)),
                ('button_url', models.CharField(default='', max_length=250)),
                ('button_text', models.CharField(default='', max_length=250)),
                ('slider_text', models.CharField(default='', max_length=500)),
                ('order', models.IntegerField(default=0)),
                ('slider_type', models.CharField(choices=[('Regular', 'Regular')], default='Regular', max_length=100)),
                ('is_archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
