# Generated by Django 4.1.7 on 2023-03-18 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SliderManagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='offer_type',
            field=models.CharField(choices=[('Regular', 'Regular')], default='Regular', max_length=100),
        ),
        migrations.AlterField(
            model_name='slider',
            name='button_url',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='slider',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
