# Generated by Django 4.1.7 on 2023-05-13 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SliderManagement", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="slider",
            name="button_text",
            field=models.CharField(default="", max_length=55),
        ),
        migrations.AlterField(
            model_name="slider",
            name="button_url",
            field=models.CharField(default="", max_length=500),
        ),
    ]
