# Generated by Django 4.1.7 on 2023-03-18 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SliderManagement', '0002_slider_offer_type_alter_slider_button_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slider',
            name='description',
        ),
    ]
