# Generated by Django 4.1.7 on 2023-03-18 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SliderManagement', '0003_remove_slider_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slider',
            old_name='offer_type',
            new_name='slider_type',
        ),
    ]
