# Generated by Django 4.1.7 on 2023-03-20 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SliderManagement', '0004_rename_offer_type_slider_slider_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='slider_text',
            field=models.CharField(default='', max_length=500),
        ),
    ]
